export enum EstadoPedido {
    PENDIENTE = 'PENDIENTE',
    ACEPTADO = 'ACEPTADO',
    EN_PREPARACION = 'EN_PREPARACION',
    LISTO = 'LISTO',
    ENTREGADO = 'ENTREGADO',
    RECHAZADO = 'RECHAZADO'
}
